package app.quarterhour.core.filter

/**
 * Looks for IPTC "digital source type" values in an image's embedded XMP that
 * mark it as generated by AI. Cameras and editors that follow the IPTC/C2PA
 * standards write these; their absence proves nothing.
 */
object ImageProvenance {
    private val MARKERS = listOf(
        "digitalsourcetype/trainedalgorithmicmedia",
        "digitalsourcetype/compositewithtrainedalgorithmicmedia",
        "digitalsourcetype/algorithmicmedia",
    )
    private val GENERATORS = listOf("dall-e", "dall·e", "midjourney", "stable diffusion", "firefly", "imagen", "openai")

    /** @param head the first ~128 KB of the image file, where XMP/JUMBF lives */
    fun isAiGenerated(head: ByteArray): Boolean {
        val text = String(head, Charsets.ISO_8859_1).lowercase()
        if (MARKERS.any { it in text }) return true
        if ("c2pa" in text && GENERATORS.any { it in text }) return true
        return false
    }
}
