package app.roadready.core

data class Question(
    val id: String,
    val topicId: String,
    val prompt: String,
    val choices: List<String>,
    val answer: Int,
    val explanation: String,
) {
    init {
        require(answer in choices.indices) { "$id: answer out of range" }
    }
}

/** Knowledge-test style questions, written from [RulesOfTheRoad]. Ids are stable: progress is saved by id. */
object QuestionBank {
    private fun q(id: String, topic: String, prompt: String, answer: String, vararg wrong: String, why: String) =
        // The correct choice goes in a position derived from the id so it isn't always first.
        (listOf(answer) + wrong).let { all ->
            val pos = Math.floorMod(id.hashCode(), all.size)
            val choices = all.drop(1).toMutableList().apply { add(pos, answer) }
            Question(id, topic, prompt, choices, pos, why)
        }

    val all: List<Question> = listOf(
        // Licensing for teens
        q("gdl1", "gdl", "What is the youngest age you can get an Oregon instruction permit?",
            "15", "14", "15½", "16", why = "You can apply for an instruction permit at 15."),
        q("gdl2", "gdl", "How many questions must you get right to pass the 35-question knowledge test?",
            "28", "25", "30", "32", why = "28 of 35 is 80%, the passing score."),
        q("gdl3", "gdl", "Who must ride with you while you drive on an instruction permit?",
            "A licensed driver at least 21, in the front passenger seat",
            "Any licensed driver, anywhere in the car",
            "A licensed driver at least 18, in the front seat",
            "A parent only",
            why = "The supervising driver must be 21+, licensed, and in the front passenger seat."),
        q("gdl4", "gdl", "Without a driver education course, how many supervised hours do you need for a provisional license?",
            "100", "50", "40", "60", why = "100 hours, or 50 hours plus an ODOT-approved traffic safety education course."),
        q("gdl5", "gdl", "With an ODOT-approved driver education course, how many supervised hours do you need?",
            "50", "25", "30", "100", why = "The course replaces 50 of the 100 hours."),
        q("gdl6", "gdl", "How long must you hold an instruction permit before getting a provisional license?",
            "6 months", "3 months", "1 year", "No minimum", why = "At least 6 months, and you must be 16."),
        q("gdl7", "gdl", "During the first 6 months of a provisional license, who can ride with you?",
            "No passengers under 20 unless they're immediate family",
            "Up to 3 passengers under 20",
            "Only passengers 25 or older",
            "Anyone, as long as they wear seat belts",
            why = "First 6 months: no passengers under 20 who aren't immediate family."),
        q("gdl8", "gdl", "In months 6 to 12 of a provisional license, how many non-family passengers under 20 may ride with you?",
            "No more than 3", "No more than 1", "No more than 5", "None", why = "The second 6 months allow at most 3."),
        q("gdl9", "gdl", "During your first year with a provisional license, you may NOT drive between:",
            "Midnight and 5 a.m., with some exceptions", "10 p.m. and 6 a.m.", "Sunset and sunrise", "9 p.m. and 5 a.m.",
            why = "Midnight to 5 a.m., except for work, home↔school event with no other ride, or with a licensed driver 25+."),
        q("gdl10", "gdl", "A 17-year-old provisional driver may use a cell phone while driving:",
            "Never, not even hands-free",
            "Only with a hands-free device",
            "Only at red lights",
            "Only to call a parent",
            why = "Drivers under 18 may not use a phone at all while driving."),
        q("gdl11", "gdl", "Provisional passenger and night limits end:",
            "After 1 year or at 18, whichever comes first",
            "At 21",
            "After 6 months",
            "After 2 years",
            why = "Whichever comes first: one year with the license, or turning 18."),

        // Speed
        q("spd1", "speed", "Unless posted otherwise, the speed limit in a residential district is:",
            "25 mph", "20 mph", "30 mph", "35 mph", why = "Residential districts: 25 mph."),
        q("spd2", "speed", "Unless posted otherwise, the speed limit in a business district is:",
            "20 mph", "15 mph", "25 mph", "30 mph", why = "Business districts: 20 mph."),
        q("spd3", "speed", "The speed limit in an alley is:",
            "15 mph", "10 mph", "20 mph", "5 mph", why = "Alleys: 15 mph."),
        q("spd4", "speed", "In a school zone when the sign's conditions apply, the speed limit is:",
            "20 mph", "15 mph", "25 mph", "10 mph", why = "School zones: 20 mph when lights flash or children are present."),
        q("spd5", "speed", "In a school zone posted \"when children are present\", children count as present when:",
            "They're in or waiting at the crosswalk, or a crossing guard is there",
            "School is in session",
            "You can see any child on the school grounds",
            "It's between 7 a.m. and 5 p.m.",
            why = "Children in the crosswalk, waiting at its curb or shoulder, or a guard helping them cross."),
        q("spd6", "speed", "Oregon's basic speed rule means:",
            "Drive no faster than is safe for conditions, even under the posted limit",
            "You may go 5 mph over the limit to pass",
            "The posted limit is always a safe speed",
            "Minimum speeds don't apply",
            why = "Speed must be reasonable and prudent for traffic, road, weather and visibility."),
        q("spd7", "speed", "If you're driving on an ocean shore where cars are allowed, the speed limit is:",
            "25 mph", "15 mph", "35 mph", "45 mph", why = "Ocean shores: 25 mph."),

        // Right of way and pedestrians
        q("row1", "rightofway", "In Oregon, which corners have a crosswalk?",
            "Every intersection, marked or unmarked",
            "Only where lines are painted",
            "Only where there's a signal",
            "Only near schools",
            why = "Every intersection is a crosswalk."),
        q("row2", "rightofway", "You stopped for a pedestrian in a crosswalk at an intersection with no signal. When can you go?",
            "When they've cleared your lane and the lane next to it",
            "As soon as they pass your front bumper",
            "When they reach the center line",
            "When they wave you on",
            why = "Stay stopped until the pedestrian clears your lane and the adjacent lane."),
        q("row3", "rightofway", "Turning at a traffic signal, you must wait until a crossing pedestrian is:",
            "Past the lane you're turning into and 6 feet into the next lane",
            "Out of your lane only",
            "On the far curb",
            "10 feet from your car",
            why = "At signals: the lane you're turning into plus 6 feet of the next lane."),
        q("row4", "rightofway", "A car ahead in the next lane has stopped at a crosswalk. You should:",
            "Stop too; someone may be crossing",
            "Pass carefully",
            "Honk and go around",
            "Change lanes to the left and continue",
            why = "Never pass a vehicle stopped for a crosswalk."),
        q("row5", "rightofway", "Two cars reach a 4-way stop at the same time. Who goes first?",
            "The car on the right",
            "The car on the left",
            "The bigger vehicle",
            "The car going straight",
            why = "When arriving together, yield to the driver on your right."),
        q("row6", "rightofway", "Entering a roundabout, you should:",
            "Yield to traffic already in the roundabout",
            "Expect traffic in the roundabout to yield to you",
            "Stop in the circle to let others in",
            "Go clockwise",
            why = "Yield to circulating traffic and travel counterclockwise."),
        q("row7", "rightofway", "A pedestrian with a white cane is at the curb. You must:",
            "Yield the right of way",
            "Honk so they know you're there",
            "Go if you have a green light",
            "Pass quickly",
            why = "Always yield to blind pedestrians with a white cane or guide dog."),

        // Signals and turns
        q("sig1", "signals", "How far before a turn must you signal?",
            "At least 100 feet", "At least 50 feet", "At least 200 feet", "Only when other cars are around",
            why = "Signal continuously for at least the last 100 feet."),
        q("sig2", "signals", "When may you turn left on a red light in Oregon?",
            "Onto a one-way street going the same way, after stopping and yielding",
            "Never",
            "Onto any street after stopping",
            "Only with a green arrow",
            why = "Left on red is legal only onto a one-way street in the direction of traffic."),
        q("sig3", "signals", "A flashing red traffic light means:",
            "Stop, then go when it's safe, like a stop sign",
            "Slow down",
            "The light is about to turn green",
            "Stop and wait for green",
            why = "Treat a flashing red like a stop sign."),
        q("sig4", "signals", "A flashing yellow left-turn arrow means:",
            "You may turn left after yielding to oncoming traffic and pedestrians",
            "You have the right of way to turn",
            "Stop and wait",
            "The left turn lane is closed",
            why = "It's a permissive turn: you must yield."),
        q("sig5", "signals", "The traffic signals at an intersection are dark because of a power outage. You should:",
            "Treat it as an all-way stop",
            "Go if no one is coming",
            "Yield only to cars on your left",
            "Go through slowly without stopping",
            why = "A dark signal is treated as a stop in all directions."),
        q("sig6", "signals", "Right on red is allowed:",
            "After a complete stop and yielding, unless a sign prohibits it",
            "Without stopping if no one is coming",
            "Only with a green arrow",
            "Never in Oregon",
            why = "Stop, yield, then turn unless a NO TURN ON RED sign is posted."),

        // Signs and markings
        q("sgn1", "signs", "An eight-sided sign always means:",
            "Stop", "Yield", "School zone", "Railroad crossing", why = "Octagons are stop signs."),
        q("sgn2", "signs", "A five-sided (pentagon) sign warns of:",
            "A school zone or school crossing", "A railroad crossing", "A no-passing zone", "A construction zone",
            why = "Pentagons mark school zones and crossings."),
        q("sgn3", "signs", "A round yellow sign means:",
            "Railroad crossing ahead", "Stop ahead", "School zone", "Hospital ahead",
            why = "The round yellow sign warns of a railroad crossing ahead."),
        q("sgn4", "signs", "Orange signs mean:",
            "Construction or a work zone", "A school zone", "Recreation area", "Hospital nearby",
            why = "Orange is used for work zones, where fines are higher with workers present."),
        q("sgn5", "signs", "Yellow lines on the road separate:",
            "Traffic going in opposite directions",
            "Traffic going the same direction",
            "Bike lanes from car lanes",
            "Parking from travel lanes",
            why = "Yellow divides opposing traffic; white divides same-direction lanes."),
        q("sgn6", "signs", "A solid yellow line on your side of the center line means:",
            "No passing", "Passing allowed when clear", "A turn lane", "A bike lane",
            why = "Don't pass across a solid yellow line on your side."),
        q("sgn7", "signs", "A center lane bordered by solid and dashed yellow lines on both sides is for:",
            "Left turns from either direction",
            "Passing slow traffic",
            "Emergency vehicles only",
            "Buses only",
            why = "It's a two-way left-turn lane, not a travel or passing lane."),
        q("sgn8", "signs", "A downward-pointing triangle sign means:",
            "Yield", "Stop", "Merge", "Warning: curve", why = "The triangle is the yield sign."),

        // Parking
        q("prk1", "parking", "How close to a fire hydrant can you park?",
            "No closer than 10 feet", "No closer than 5 feet", "No closer than 15 feet", "No closer than 20 feet",
            why = "Stay at least 10 feet from a hydrant."),
        q("prk2", "parking", "How close can you park to a crosswalk at an intersection?",
            "No closer than 20 feet", "No closer than 10 feet", "No closer than 30 feet", "No closer than 50 feet",
            why = "Stay at least 20 feet from a crosswalk at an intersection."),
        q("prk3", "parking", "How close can you park to a railroad crossing?",
            "No closer than 50 feet", "No closer than 20 feet", "No closer than 30 feet", "No closer than 100 feet",
            why = "Stay at least 50 feet from a railroad crossing."),
        q("prk4", "parking", "Parking downhill next to a curb, turn your front wheels:",
            "Toward the curb", "Away from the curb", "Straight ahead", "It doesn't matter",
            why = "If the car rolls, the wheels stop against the curb."),
        q("prk5", "parking", "Parking uphill next to a curb, turn your front wheels:",
            "Away from the curb", "Toward the curb", "Straight ahead", "Toward the road edge",
            why = "If the car rolls back, the back of the front tire catches the curb."),
        q("prk6", "parking", "When parallel parking, your wheels must be within how far of the curb?",
            "12 inches", "6 inches", "18 inches", "24 inches", why = "Within 12 inches of the curb."),

        // Sharing the road
        q("shr1", "sharing", "Passing a bicyclist at more than 35 mph, how much room must you leave?",
            "Enough that you wouldn't hit them if they fell into your lane",
            "Exactly 3 feet",
            "One car length",
            "None if they're in a bike lane",
            why = "Oregon's rule is room enough to avoid a rider who falls into your lane."),
        q("shr2", "sharing", "You're turning right across a bike lane. You must:",
            "Yield to bicyclists in the bike lane",
            "Turn first; bikes must yield to cars",
            "Honk to warn them",
            "Turn from the bike lane",
            why = "A bike lane is a lane; yield before turning across it."),
        q("shr3", "sharing", "At a railroad crossing where you must stop, stop:",
            "Between 15 and 50 feet from the nearest rail",
            "Right at the tracks",
            "At least 100 feet away",
            "Between 5 and 10 feet from the rail",
            why = "Between 15 and 50 feet from the nearest rail."),
        q("shr4", "sharing", "If you can't see a truck driver's mirrors:",
            "The driver can't see you",
            "You're at a safe following distance",
            "You should pass on the right",
            "The truck is about to stop",
            why = "You're in the truck's blind spot."),
        q("shr5", "sharing", "Before you start across railroad tracks you should make sure:",
            "There's room for your whole car on the other side",
            "The car ahead has started across",
            "Your radio is off",
            "Your hazard lights are on",
            why = "Never stop on the tracks."),

        // School buses and emergency vehicles
        q("emg1", "emergency", "A school bus ahead on a 4-lane undivided road is flashing red lights. Which drivers must stop?",
            "Drivers in both directions",
            "Only drivers behind the bus",
            "Only drivers in the bus's lane",
            "No one, on a 4-lane road",
            why = "Oregon requires stopping in both directions on any undivided road."),
        q("emg2", "emergency", "You don't have to stop for a school bus flashing red lights when:",
            "It's on the other side of a divided highway with an unpaved median or barrier",
            "You're on a 4-lane road going the other way",
            "No children are visible",
            "You're running late",
            why = "Only an unpaved median or barrier between you exempts the other side."),
        q("emg3", "emergency", "An ambulance with siren and lights is coming. You should:",
            "Pull to the right edge and stop until it passes",
            "Speed up to get out of the way",
            "Stop where you are",
            "Pull to the left",
            why = "Move to the right and stop."),
        q("emg4", "emergency", "You approach a car stopped on the shoulder with hazard lights on, and you can't change lanes. You must:",
            "Slow to at least 5 mph under the speed limit",
            "Keep your speed",
            "Stop behind it",
            "Honk as you pass",
            why = "Oregon's move-over law covers any stopped vehicle showing hazards or distress."),

        // Alcohol and distraction
        q("imp1", "impaired", "For drivers under 21, the legal blood alcohol limit is:",
            "Any amount is illegal", "0.02%", "0.05%", "0.08%",
            why = "Oregon has zero tolerance for drivers under 21."),
        q("imp2", "impaired", "For drivers 21 and older, DUII starts at a BAC of:",
            "0.08%", "0.10%", "0.05%", "0.12%", why = "0.08% or more."),
        q("imp3", "impaired", "Under implied consent, refusing a breath test after a DUII arrest:",
            "Suspends your license",
            "Is allowed with no penalty",
            "Means you can't be charged",
            "Only matters for commercial drivers",
            why = "Driving means you've agreed to testing; refusing brings a suspension."),
        q("imp4", "impaired", "Which can lead to a DUII?",
            "Alcohol, cannabis, or medicine that impairs you",
            "Only alcohol",
            "Only illegal drugs",
            "Only alcohol over 0.08%",
            why = "Any impairing substance can lead to DUII."),

        // Night and weather
        q("cnd1", "conditions", "You must use headlights:",
            "From sunset to sunrise and when you can't see 1,000 feet ahead",
            "Only after dark",
            "Only in rain",
            "From 30 minutes after sunset",
            why = "Sunset to sunrise, and whenever visibility is under 1,000 feet."),
        q("cnd2", "conditions", "Dim your high beams when an oncoming car is within:",
            "500 feet", "200 feet", "1,000 feet", "100 feet", why = "Within 500 feet of oncoming traffic."),
        q("cnd3", "conditions", "Dim your high beams when you're following a car within:",
            "350 feet", "100 feet", "500 feet", "1,000 feet", why = "Within 350 feet when following."),
        q("cnd4", "conditions", "In good conditions, keep a following distance of at least:",
            "2 seconds", "1 second", "1 car length", "10 feet", why = "At least 2 seconds; more in bad conditions."),
        q("cnd5", "conditions", "If your car starts to hydroplane, you should:",
            "Ease off the gas and steer straight",
            "Brake hard",
            "Speed up to regain traction",
            "Turn the wheel sharply",
            why = "Let the car slow down until the tires grip again."),
        q("cnd6", "conditions", "In fog you should use:",
            "Low beams", "High beams", "Parking lights only", "No lights",
            why = "High beams reflect off fog and make it harder to see."),
        q("cnd7", "conditions", "Which part of the road usually freezes first?",
            "Bridges and shaded areas", "Uphill stretches", "Intersections", "Sunny straightaways",
            why = "Bridges lose heat from below; shade keeps ice longer."),
        q("cnd8", "conditions", "If your car skids, you should:",
            "Look and steer where you want to go",
            "Slam on the brakes",
            "Steer the opposite way you want to go",
            "Take your hands off the wheel",
            why = "Steer where you want the car to go."),

        // Crashes
        q("crs1", "crashes", "Within how many hours must you report a reportable crash to DMV?",
            "72 hours", "24 hours", "10 days", "30 days", why = "Within 72 hours."),
        q("crs2", "crashes", "A crash must be reported to DMV if your car's damage is more than:",
            "$2,500", "$500", "$1,000", "$5,000", why = "Over $2,500, or anyone is hurt or killed."),
        q("crs3", "crashes", "You back into a parked car and the owner isn't around. You should:",
            "Find the owner or leave a note with your contact information",
            "Drive away if the damage is small",
            "Wait 10 minutes, then leave",
            "Call your parents and leave",
            why = "Leaving without identifying yourself is hit-and-run."),
        q("crs4", "crashes", "Your brakes suddenly fail. First you should:",
            "Pump the brake pedal",
            "Turn off the engine",
            "Shift into park",
            "Steer onto the shoulder at full speed",
            why = "Pump the pedal, downshift, then use the parking brake gently."),

        // Seat belts
        q("pas1", "passengers", "A child under 2 must ride:",
            "In a rear-facing car seat", "In a forward-facing seat", "In a booster", "On a parent's lap",
            why = "Oregon requires rear-facing seats for children under 2."),
        q("pas2", "passengers", "Who is responsible for making sure passengers under 16 are buckled?",
            "The driver", "The passengers' parents", "The oldest passenger", "No one", why = "The driver."),
    )

    fun byTopic(topicId: String): List<Question> = all.filter { it.topicId == topicId }
    fun byId(id: String): Question? = all.firstOrNull { it.id == id }
}
